default_roles:
  - system
  - ssh
  - sshfs
  - git
  # - alacrity
  # - tmux
  - awesome
  - wezterm
  - zsh
  - fzf
  - go
  - npm
  - nvm
  - python
  - ruby
  - rust
  - lua
  - neofetch
  - neovim
  - tldr
  - spf
  - flatpak
  - fonts
  # - docker
  # - brave
  # - obsidian
  # - gcloud
  # - bruno
  # - dbeaver
  # - discord
  # - slack

home: "{{ lookup('ansible.builtin.env', 'HOME') }}"
dev: "{{ home }}/dev"
