---
- name: "Ensure required packages are installed (Debian/Ubuntu)"
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  become: true

- name: "Download Brave's GPG key"
  get_url:
    url: https://brave-browser-apt-release.s3.brave.com/brave-browser-archive-keyring.gpg
    dest: /usr/share/keyrings/brave-browser-archive-keyring.gpg
    mode: '0644'
  become: true

- name: "Add Brave's repository (Debian/Ubuntu)"
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/brave-browser-release.list
    line: "deb [signed-by=/usr/share/keyrings/brave-browser-archive-keyring.gpg arch=amd64] https://brave-browser-apt-release.s3.brave.com/ stable main"
    create: yes
    state: present
  become: true

- name: "Update package cache and install Brave browser (Debian/Ubuntu)"
  ansible.builtin.apt:
    update_cache: yes
    name: brave-browser
    state: latest
  become: true

