---
- name: "Install"
  community.general.flatpak:
    name: "md.obsidian.Obsidian"
    state: present

- name: "Create vaults dir"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/vaults"
    state: directory
