---
- name: "Ensure required packages are installed (Debian/Ubuntu)"
  ansible.builtin.apt:
    name: apt-transport-https
    state: present
  become: yes

- name: "Check if Google Cloud SDK repository exists"
  ansible.builtin.shell:
    cmd: grep -q "https://packages.cloud.google.com/apt" /etc/apt/sources.list.d/*
  register: repo_exists
  ignore_errors: yes
  become: true

- name: "Add Google Cloud SDK repository (Debian/Ubuntu)"
  ansible.builtin.lineinfile:
    path: /etc/apt/sources.list.d/google-cloud-sdk.list
    line: "deb [signed-by=/usr/share/keyrings/cloud.google.gpg] https://packages.cloud.google.com/apt cloud-sdk main"
    create: yes
    state: present
  become: true
  when: repo_exists.rc != 0

- name: "Check if Google Cloud SDK GPG key exists"
  ansible.builtin.stat:
    path: /usr/share/keyrings/cloud.google.gpg
  register: key_exists

- name: "Add Google Cloud SDK GPG key (Debian/Ubuntu)"
  shell: |
    curl https://packages.cloud.google.com/apt/doc/apt-key.gpg | gpg --dearmor -o /usr/share/keyrings/cloud.google.gpg
  become: true
  args:
    creates: /usr/share/keyrings/cloud.google.gpg

- name: "Update package cache and install Google Cloud SDK (Debian/Ubuntu)"
  ansible.builtin.apt:
    update_cache: yes
    name: google-cloud-sdk
    state: latest
  become: true

- name: "Install additional components"
  ansible.builtin.apt:
    name: "{{ item }}"
    state: latest
  loop:
    - google-cloud-sdk-app-engine-go
    - google-cloud-sdk-cloud-build-local
    - google-cloud-sdk-pubsub-emulator
  become: true
