---
- name: "{{ role_name }} | Checking for Distribution Config: {{ distribution_name }}"
  ansible.builtin.stat:
    path: "{{ role_path }}/tasks/{{ distribution_name }}.yml"
  register: distribution_config

- name: "{{ role_name }} | Run Tasks: {{ distribution_name }}"
  ansible.builtin.include_tasks: "{{ distribution_name }}.yml"
  when: distribution_config.stat.exists
