---
- name: "Install build prerequisites"
  ansible.builtin.apt:
    name:
      - ninja-build
      - cmake
      - gettext
      - curl
      - build-essential
    state: present
  become: yes

- name: "Create ~/src directory if it doesn't exist"
  ansible.builtin.file:
    path: "{{ ansible_user_dir }}/src"
    state: directory

- name: Fetch Neovim tags with force
  ansible.builtin.shell: |
    git -C "{{ ansible_user_dir }}/src/neovim" fetch --tags --force origin
  become: true

- name: "Clone or Update Neovim repository"
  ansible.builtin.git:
    repo: https://github.com/neovim/neovim.git
    dest: "{{ ansible_user_dir }}/src/neovim"
    version: master
  register: git_status

- name: "Build and install Neovim if updated"
  block:
    - name: "Build Neovim"
      ansible.builtin.shell:
        cmd: make CMAKE_BUILD_TYPE="{{ build_type }}"
        chdir: "{{ ansible_user_dir }}/src/neovim"

    - name: "Install Neovim"
      ansible.builtin.shell:
        cmd: make install
        chdir: "{{ ansible_user_dir }}/src/neovim"
      become: yes
  when: git_status.changed == True
